[2021-10-06 16:20:41,567] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Pipeline.get_data2 2021-10-06T16:20:39.977699+00:00 [queued]>
[2021-10-06 16:20:41,577] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Pipeline.get_data2 2021-10-06T16:20:39.977699+00:00 [queued]>
[2021-10-06 16:20:41,578] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-10-06 16:20:41,578] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-10-06 16:20:41,578] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-10-06 16:20:41,589] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): get_data2> on 2021-10-06T16:20:39.977699+00:00
[2021-10-06 16:20:41,595] {standard_task_runner.py:52} INFO - Started process 164 to run task
[2021-10-06 16:20:41,598] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Pipeline', 'get_data2', '2021-10-06T16:20:39.977699+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/P.py', '--cfg-path', '/tmp/tmp36daykwr', '--error-file', '/tmp/tmp388nsc2_']
[2021-10-06 16:20:41,598] {standard_task_runner.py:77} INFO - Job 3: Subtask get_data2
[2021-10-06 16:20:41,632] {logging_mixin.py:104} INFO - Running <TaskInstance: Pipeline.get_data2 2021-10-06T16:20:39.977699+00:00 [running]> on host 8a718b72cb7e
[2021-10-06 16:20:41,669] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=datath
AIRFLOW_CTX_DAG_ID=Pipeline
AIRFLOW_CTX_TASK_ID=get_data2
AIRFLOW_CTX_EXECUTION_DATE=2021-10-06T16:20:39.977699+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-06T16:20:39.977699+00:00
[2021-10-06 16:20:44,679] {python.py:151} INFO - Done. Returned value was: None
[2021-10-06 16:20:44,690] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=Pipeline, task_id=get_data2, execution_date=20211006T162039, start_date=20211006T162041, end_date=20211006T162044
[2021-10-06 16:20:44,716] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-06 16:20:44,741] {local_task_job.py:151} INFO - Task exited with return code 0
